### ISSUE TITLE
Unit tests and headless GUI

### ISSUE THREAD

**Issue by mrbkt** [kestreltechnology/eclipse-kt-advance#14]
Add some unit tests for the plugins and integration with the Eclipse GUI.  This does not have to be exhaustive, but it should establish a GUI and non-GUI testing framework that works properly with the Maven environment.  No preferences for which testing framework to use, although it should work under headless mode when Travis runs the tests.

**Comment by mrbkt** [comment]
I think this enhancement/issue is nearly ready to be closed.  Are there any remaining uncertainties about running RPCTT headless or under a Travis matrix build?

**Comment by msiz** [comment]
Yes, I've almost finished. Going to add the last tests for Statistics Views today.
Tests run fine with xvfb display on Travis.
What do you mean by "matrix" - different OS? I think Travis currently supports only Linux (default) and MacOS: https://docs.travis-ci.com/user/multi-os/
Haven't tried it yet.
If we want to run automatic tests on Windows, probably would need to add different CI like https://www.appveyor.com/

**Comment by mrbkt** [comment]
Yes, I was thinking Linux/MacOS for matrix.  I suppose we could do Java 7/8/9 that way too, but I don't know if there is an Eclipse Neon dependency on the JDK version.   New editions of Eclipse will emerge soon.  Let's not play with the JDK version right now.  

Having Windows included eventually would be good; I haven't used Appveyor but will look into it.  We don't yet build the KT Advance analyzer for Windows, but our users could employ the analyzer in a Docker container with results shared on an attached volume to Eclipse on Windows.

**Comment by msiz** [comment]
I think current tests set covers almost all the functionality. Some minor bugs have been fixed.
We can add extra tests in the future if we find out something is missing or new features would be added.

**Comment by mrbgg** [comment]
I'm completely happy with the configuration and state of the tests.  Nice work.  We can add more later as needed.  I'm glad you figured out how to make this work.   We can close this enhancement/issue.

**Comment by mrbkt** [comment]
I'm completely happy with the configuration and state of the tests. Nice work. We can add more later as needed. I'm glad you figured out how to make this work. We can close this enhancement/issue.
