### ISSUE TITLE
Integrate repo with Travis-CI for test and build

### ISSUE THREAD

**Issue by mrbkt** [kestreltechnology/eclipse-kt-advance#15]
Travis-CI integration has been enabled.  What remains is to connect the Java/Maven actions with the test and build services offered in Travis.  Travis should be able to run and report the tests, to build any automated documentation, and to perform packaging and deployment.

**Comment by msiz** [comment]
Done. Tests run with Travis on Linux and MacOS (+ Windows with Appveyor).
Deployment will be implemented in #16.
Currently there is no documentation to package.

**Comment by mrbkt** [comment]
Okay to close
