### ISSUE TITLE
Feature and update site, then deployment

### ISSUE THREAD

**Issue by mrbkt** [kestreltechnology/eclipse-kt-advance#16]
Add an Eclipse feature project to collect all the plugins as a KT Advance feature.  Then, using the feature, add the update site project.  Make Travis do the update site build.  Make Travis do GitHub release that builds the update site.  We will then automate deployment of the update site to an AWS S3 bucket and will create a DNS entry to point to the update site on S3.

**Comment by msiz** [comment]
Update site project was added. Travis builds it as one of the project modules with maven.
Plugin versions can be updated with "tycho-versions-plugin" plugin:
`mvn -Dtycho.mode=maven org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=x`
This modifies all the manifest, feature and pom files within the project, setting corresponding version everywhere.
To make a release it is required to: update version; commit changes with some tag; push changes to the repository.
Travis Linux machine will do a release after a successful build, available here: https://github.com/kestreltechnology/eclipse-kt-advance/releases

Is it sufficient for now?
Uploading update site to S3 should not be a problem as well: https://docs.travis-ci.com/user/deployment/s3/

**Comment by mrbkt** [comment]
Yes, looks good.  I’ve posted an S3 pull request too, but it is untested because I haven’t done these steps below..

**Comment by msiz** [comment]
GitHub/S3 releases are performed automatically by Travis on a tagged commit. So closing the ticket.
